# fly.toml app configuration file generated for staticman-joegoldin on 2024-08-10T07:41:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'staticman-joegoldin'
primary_region = 'lax'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
